[package]
name = "ifconfig-neon-toys"
version = "0.1.0"
edition = "2021"



[dependencies]
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.33.0", features = ["full"] }
